os: windows
python: "3.7"
language: sh
before_install:
  - choco install python3
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  - python -m pip install --upgrade pip wheel
  - pip install pipenv
install:
  - pipenv install --dev --deploy
script:
  - pipenv run flake8
  - pipenv run pytest
